name: Build-and-run-Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get azdo wi link step
        uses: solidify/github-action-azdo-link@v0.9.2
        with:
          organization: 'Maneric'
          projectName: 'MyFirstProject'
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
